server:
  port: 8083

spring:
  application:
    name: job-manager
  profiles:
    active: dev

# --- 공통 로깅/관리 설정 ---
logging:
  level:
    org.hibernate.SQL: info

management:
  endpoints:
    web:
      exposure:
        include: health,info

# === 토스/결제 공통 설정 ===
toss:
  base-url: https://api.tosspayments.com/v1
  secret-key: ${TOSS_SECRET_KEY:}

payments:
  success-url: ${PAY_SUCCESS_URL:https://localhost:5173/pay/success}
  fail-url: ${PAY_FAIL_URL:https://localhost:5173/pay/fail}

---
spring:
  datasource:
    url: jdbc:mysql://mysql-1bd69c46-capstone2.g.aivencloud.com:25590/job_manager?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_Ozi4pud2pUgpPbOzJ9V
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true

jwt:
  secret: "12345678901234567890123456789012"
  expiration-ms: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework: DEBUG
    com.jobmanager: DEBUG

bizapi:
  base-url: "https://api.odcloud.kr/api/nts-businessman"
  service-key: "cb32731267cdcc15e0f5c1acd046a6420bc0ee844fd25921b737ca43d81a7dcc"