server:
  port: 8083

spring:
  application:
    name: job-manager
  profiles:
    active: dev

# --- 공통 로깅/관리 설정 ---
logging:
  level:
    org.hibernate.SQL: info

management:
  endpoints:
    web:
      exposure:
        include: health,info


---
spring:
  datasource:
    url: jdbc:mysql://mysql-1bd69c46-capstone2.g.aivencloud.com:25590/job_manager?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_Ozi4pud2pUgpPbOzJ9V
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true

jwt:
  secret: "12345678901234567890123456789012"
  expiration-ms: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework: DEBUG
    com.jobmanager: DEBUG