server:
  port: 8083

spring:
  application:
    name: job-manager
  profiles:
    active: dev

# --- 공통 로깅/관리 설정 ---
logging:
  level:
    org.hibernate.SQL: info

management:
  endpoints:
    web:
      exposure:
        include: health,info

# === 토스/결제 공통 설정 ===
toss:
  base-url: https://api.tosspayments.com/v1           # 결제승인/취소 엔드포인트 베이스
  secret-key: ${TOSS_SECRET_KEY:}                     # 서버 전용 시크릿키 (절대 프론트 노출 금지)

payments:
  success-url: ${PAY_SUCCESS_URL:https://localhost:5173/pay/success}  # 프론트 success 라우트
  fail-url: ${PAY_FAIL_URL:https://localhost:5173/pay/fail}           # 프론트 fail 라우트

---
spring:
  datasource:
    url: jdbc:mysql://mysql-1bd69c46-capstone2.g.aivencloud.com:25590/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_Ozi4pud2pUgpPbOzJ9V

  jpa:
    hibernate:
      ddl-auto: none          # 이미 테이블 존재 → none (필요하면 validate)
    open-in-view: false
    properties:
      hibernate.format_sql: true
      show_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: "12345678901234567890123456789012"
  expiration-ms: 3600000   # 1시간 (밀리초)
